#mysqldata:
#  image: harshjv/mysql-data:0.9.16-1.0

composerdata:
  image: harshjv/composer-data:0.9.16-1.0

mysql:
#  image: harshjv/mysql:0.9.16-1.0
  image: mysql:5.6
  environment:
    - MYSQL_ROOT_PASSWORD=root
  # volumes_from:
    # - mysqldata
  ports:
    - "3306:3306"
  volumes:
    - ./data:/var/lib/mysql

# phpnginx:
#   image: harshjv/php-nginx:0.9.16-1.0
#   volumes_from:
#     - composerdata
#   links:
#     - mysql
#   ports:
#     - "80:80"
#   volumes:
#     - ./nginx:/etc/nginx/sites-available
#     - ./:/var/www

apache-php:
  image: gumplei/apache-php:latest
  links:
    - mysql
  ports:
    - "80:80"
  volumes:
    - ./apache:/etc/apache2/sites-available
    - ./:/var/www/html
    - ./composerdata:/home/ubuntu

#gulp:
#  build: ./gulp-docker
#  volumes:
#    - ./src:/data
