#mysqldata:
#  image: harshjv/mysql-data:0.9.16-1.0

composerdata:
  image: harshjv/composer-data:0.9.16-1.0

mysql:
  image: harshjv/mysql:0.9.16-1.0
  environment:
    MYSQL_PASS: root
  # volumes_from:
    # - mysqldata
  volumes:
    - ./data:/var/lib/mysql

# phpnginx:
#   image: harshjv/php-nginx:0.9.16-1.0
#   volumes_from:
#     - composerdata
#   links:
#     - mysql
#   ports:
#     - "80:80"
#   volumes:
#     - ./nginx:/etc/nginx/sites-available
#     - ./:/var/www

apache-php:
  build: ./apache-php-docker
  links:
    - mysql
  ports:
    - "80:80"
  volumes:
    - ./apache:/etc/apache2/sites-available
    - ./:/var/www/html
    - ./composerdata:/home/ubuntu

gulp:
  image: harshjv/bower-gulp:1.0
  volumes:
    - ./src:/data
