version: "3"
services:
  mysql:
  #  image: harshjv/mysql:0.9.16-1.0
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yoliving
      MYSQL_USER: dbusr
      MYSQL_PASSWORD: password123
    ports:
      - "3366:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      yoliving:
        aliases:
          - mysql

  apache-php:
    image: gumplei/apache-php:latest
    ports:
      - "80:80"
    volumes:
      - ./apache:/etc/apache2/sites-available
      - ./src:/var/www/html
    networks:
      yoliving:
        aliases:
          - apache

networks:
  yoliving: